var buster = require("buster");
var tokenizer = require("../tokenizer.js");

buster.testCase("tokenizer tire kick", {
	"combined": function() {
		t = tokenizer.New("1 + 2.2 - 3.4e56 * \"abc\" && foo!=$bar / (_baz ? quux0 : ok_I_get_it)");
		assert.equals(t.tok_type, "number");
		assert.equals(t.val, "1");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "op");
		assert.equals(t.val, "+");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "number");
		assert.equals(t.val, "2.2");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "op");
		assert.equals(t.val, "-");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "number");
		assert.equals(t.val, "3.4e56");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "op");
		assert.equals(t.val, "*");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "string");
		assert.equals(t.val, "abc");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "op");
		assert.equals(t.val, "&&");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "name");
		assert.equals(t.val, "foo");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "op");
		assert.equals(t.val, "!=");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "name");
		assert.equals(t.val, "$bar");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "op");
		assert.equals(t.val, "/");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "op");
		assert.equals(t.val, "(");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "name");
		assert.equals(t.val, "_baz");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "op");
		assert.equals(t.val, "?");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "name");
		assert.equals(t.val, "quux0");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "op");
		assert.equals(t.val, ":");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "name");
		assert.equals(t.val, "ok_I_get_it");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "op");
		assert.equals(t.val, ")");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "over");
		assert.equals(t.val, "end of stream");
		assert.isNull(t.toke());
		assert.equals(t.tok_type, "over");
		assert.equals(t.val, "end of stream");
	}
});

